namespace FYP_V2
{
    [bindable]
    [default_interface]
    runtimeclass ShareDataViewModel
    {
        ShareDataViewModel();

        vector<Graph> graphList;
        vector<Node> currentNodes;
        vector<Edge> currentEdges;
        int currentGraphIdx;
    }
}
